### ISSUE TITLE
the script doesn't want to work

### ISSUE THREAD

**Issue by Negatifff** [rjuang/flstudio-arturia-keylab-mk2#1]
Hello.
I tried to install your script: Firmware 1.2.4 (like yours), Windows 10, FL Studio 20.7.2. installed according to the instructions. FL studio sees scripts, install gives, but does not work. I install for MIDIIN2 (KeyLab mkII 61) - https://c.radikal.ru/c03/2101/f2/5460f5e265ec.png. when the keylab is restarted, there is no sign "Connected to FL Studio" on the screen. when I put Mackie Control Universal - it works (it is clear that not everything).
Please tell me what I did wrong?

**Comment by rjuang** [comment]
I use the plugins module which isn't supported in 20.7.2.  I have a patch going in to fix this.

**Comment by rjuang** [comment]
Fix is in.
